export ROS_HOSTNAME=localhost
export ROS_MASTER_URI=http://localhost:11311
export WORKSPACE=/home/ubuntu/catkin_ws
source /opt/ros/noetic/setup.bash
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/ubuntu/csc376/build
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/ubuntu/csc376/models

alias vim=vi
